# Generated by Django 3.1.4 on 2021-01-22 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('concert_date', models.DateField(verbose_name='concert date')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=100)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.concert')),
            ],
        ),
    ]
